import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const goals = sqliteTable("goals", {
  id: text("id").primaryKey(),
  schemaVersion: integer("schema_version").notNull().default(1),
  goalType: text("goal_type").notNull(),
  customGoalLabel: text("custom_goal_label"),
  underlyingAsset: text("underlying_asset").notNull(),
  protectedValueUsd: text("protected_value_usd").notNull(),
  deadline: text("deadline").notNull(),
  maxLossBps: integer("max_loss_bps").notNull(),
  maxPremiumUsd: text("max_premium_usd"),
  originalUserMessage: text("original_user_message").notNull(),
  status: text("status").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  check("goals_schema_version_check", sql`${table.schemaVersion} = 1`),
  check("goals_max_loss_bps_check", sql`${table.maxLossBps} >= 0 AND ${table.maxLossBps} <= 9999`),
  check("goals_custom_label_check", sql`(${table.goalType} = 'custom' AND ${table.customGoalLabel} IS NOT NULL) OR (${table.goalType} <> 'custom' AND ${table.customGoalLabel} IS NULL)`),
  index("goals_status_updated_idx").on(table.status, table.updatedAt),
  index("goals_deadline_idx").on(table.deadline),
]);

export const protectionCandidates = sqliteTable("protection_candidates", {
  id: text("id").primaryKey(),
  goalId: text("goal_id").notNull().references(() => goals.id, { onDelete: "cascade" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  source: text("source").notNull(),
  protocolOrderId: text("protocol_order_id"),
  underlyingAsset: text("underlying_asset").notNull(),
  optionType: text("option_type").notNull(),
  strikeUsd: text("strike_usd").notNull(),
  expiry: text("expiry").notNull(),
  settlementTokenAddress: text("settlement_token_address").notNull(),
  settlementTokenSymbol: text("settlement_token_symbol").notNull(),
  settlementTokenDecimals: integer("settlement_token_decimals").notNull(),
  premiumAmountBaseUnits: text("premium_amount_base_units").notNull(),
  premiumUsd: text("premium_usd").notNull(),
  quantityBaseUnits: text("quantity_base_units").notNull(),
  quantityUnderlying: text("quantity_underlying").notNull(),
  maxPremiumLossUsd: text("max_premium_loss_usd").notNull(),
  estimatedFloorUsd: text("estimated_floor_usd").notNull(),
  deadlineGapHours: integer("deadline_gap_hours").notNull(),
  goalCoverageBps: integer("goal_coverage_bps").notNull(),
  availableQuantityBaseUnits: text("available_quantity_base_units"),
  status: text("status").notNull(),
  rejectionReasonsJson: text("rejection_reasons_json").notNull().default("[]"),
  protocolRawJson: text("protocol_raw_json").notNull(),
  scenariosJson: text("scenarios_json").notNull(),
  marketAsOf: text("market_as_of").notNull(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
}, (table) => [
  check("candidates_schema_version_check", sql`${table.schemaVersion} = 1`),
  check("candidates_token_decimals_check", sql`${table.settlementTokenDecimals} >= 0 AND ${table.settlementTokenDecimals} <= 255`),
  check("candidates_deadline_gap_check", sql`${table.deadlineGapHours} >= 0`),
  check("candidates_coverage_check", sql`${table.goalCoverageBps} >= 0 AND ${table.goalCoverageBps} <= 10000`),
  index("candidates_goal_status_idx").on(table.goalId, table.status),
  index("candidates_expiry_idx").on(table.expiry),
  index("candidates_source_order_idx").on(table.source, table.protocolOrderId),
  uniqueIndex("candidates_one_selected_per_goal_idx").on(table.goalId).where(sql`${table.status} = 'selected'`),
]);

export const gonkaInferences = sqliteTable("gonka_inferences", {
  id: text("id").primaryKey(),
  goalId: text("goal_id").references(() => goals.id, { onDelete: "set null" }),
  candidateId: text("candidate_id").references(() => protectionCandidates.id, { onDelete: "set null" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  purpose: text("purpose").notNull(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  requestId: text("request_id"),
  status: text("status").notNull(),
  inputHash: text("input_hash").notNull(),
  latencyMs: integer("latency_ms"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  rawResponseJson: text("raw_response_json"),
  createdAt: text("created_at").notNull(),
  completedAt: text("completed_at"),
}, (table) => [
  check("inferences_schema_version_check", sql`${table.schemaVersion} = 1`),
  check("inferences_provider_check", sql`${table.provider} = 'gonka'`),
  check("inferences_latency_check", sql`${table.latencyMs} IS NULL OR ${table.latencyMs} >= 0`),
  index("inferences_goal_purpose_created_idx").on(table.goalId, table.purpose, table.createdAt),
  index("inferences_candidate_purpose_idx").on(table.candidateId, table.purpose),
  uniqueIndex("inferences_request_id_idx").on(table.requestId).where(sql`${table.requestId} IS NOT NULL`),
]);

export const councilDecisions = sqliteTable("council_decisions", {
  id: text("id").primaryKey(),
  goalId: text("goal_id").notNull().references(() => goals.id, { onDelete: "cascade" }),
  candidateId: text("candidate_id").notNull().references(() => protectionCandidates.id, { onDelete: "cascade" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  attempt: integer("attempt").notNull(),
  status: text("status").notNull(),
  rulesetVersion: text("ruleset_version").notNull(),
  approvedReviewCount: integer("approved_review_count").notNull(),
  rejectedReviewCount: integer("rejected_review_count").notNull(),
  uncertainReviewCount: integer("uncertain_review_count").notNull(),
  blockedReasonsJson: text("blocked_reasons_json").notNull().default("[]"),
  createdAt: text("created_at").notNull(),
}, (table) => [
  check("decisions_schema_version_check", sql`${table.schemaVersion} = 1`),
  check("decisions_attempt_check", sql`${table.attempt} >= 1`),
  check("decisions_counts_check", sql`${table.approvedReviewCount} >= 0 AND ${table.approvedReviewCount} <= 3 AND ${table.rejectedReviewCount} >= 0 AND ${table.rejectedReviewCount} <= 3 AND ${table.uncertainReviewCount} >= 0 AND ${table.uncertainReviewCount} <= 3`),
  uniqueIndex("decisions_candidate_attempt_idx").on(table.candidateId, table.attempt),
  index("decisions_goal_created_idx").on(table.goalId, table.createdAt),
  index("decisions_candidate_created_idx").on(table.candidateId, table.createdAt),
]);

export const councilReviews = sqliteTable("council_reviews", {
  id: text("id").primaryKey(),
  decisionId: text("decision_id").notNull().references(() => councilDecisions.id, { onDelete: "cascade" }),
  inferenceId: text("inference_id").notNull().references(() => gonkaInferences.id),
  schemaVersion: integer("schema_version").notNull().default(1),
  role: text("role").notNull(),
  model: text("model").notNull(),
  requestId: text("request_id").notNull(),
  verdict: text("verdict").notNull(),
  confidenceBps: integer("confidence_bps").notNull(),
  summary: text("summary").notNull(),
  concernsJson: text("concerns_json").notNull().default("[]"),
  requiredDisclosuresJson: text("required_disclosures_json").notNull().default("[]"),
  createdAt: text("created_at").notNull(),
}, (table) => [
  check("reviews_schema_version_check", sql`${table.schemaVersion} = 1`),
  check("reviews_confidence_check", sql`${table.confidenceBps} >= 0 AND ${table.confidenceBps} <= 10000`),
  uniqueIndex("reviews_decision_role_idx").on(table.decisionId, table.role),
  uniqueIndex("reviews_inference_idx").on(table.inferenceId),
  index("reviews_decision_idx").on(table.decisionId),
]);

export const trades = sqliteTable("trades", {
  id: text("id").primaryKey(),
  goalId: text("goal_id").notNull().references(() => goals.id, { onDelete: "restrict" }),
  candidateId: text("candidate_id").notNull().references(() => protectionCandidates.id, { onDelete: "restrict" }),
  councilDecisionId: text("council_decision_id").notNull().references(() => councilDecisions.id, { onDelete: "restrict" }),
  schemaVersion: integer("schema_version").notNull().default(1),
  idempotencyKey: text("idempotency_key").notNull(),
  walletAddress: text("wallet_address").notNull(),
  chainId: integer("chain_id").notNull(),
  status: text("status").notNull(),
  quoteFingerprint: text("quote_fingerprint").notNull(),
  previewExpiresAt: text("preview_expires_at").notNull(),
  settlementTokenAddress: text("settlement_token_address").notNull(),
  premiumAmountBaseUnits: text("premium_amount_base_units").notNull(),
  premiumUsd: text("premium_usd").notNull(),
  txHash: text("tx_hash"),
  protocolPositionId: text("protocol_position_id"),
  failureCode: text("failure_code"),
  failureMessage: text("failure_message"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  submittedAt: text("submitted_at"),
  confirmedAt: text("confirmed_at"),
}, (table) => [
  check("trades_schema_version_check", sql`${table.schemaVersion} = 1`),
  check("trades_chain_id_check", sql`${table.chainId} = 8453`),
  check("trades_idempotency_length_check", sql`length(${table.idempotencyKey}) BETWEEN 16 AND 128`),
  uniqueIndex("trades_idempotency_key_idx").on(table.idempotencyKey),
  uniqueIndex("trades_tx_hash_idx").on(table.txHash).where(sql`${table.txHash} IS NOT NULL`),
  index("trades_goal_created_idx").on(table.goalId, table.createdAt),
  index("trades_wallet_created_idx").on(table.walletAddress, table.createdAt),
  index("trades_status_updated_idx").on(table.status, table.updatedAt),
]);
