/**
 * Exports one real, completed run into the presentation fixture.
 *
 * The presentation flow must not invent Gonka request IDs, models or verdicts, so the
 * fixture is generated from the database rather than written by hand. Re-run this if the
 * captured run is ever replaced:
 *
 *   npx tsx --env-file=.env.local scripts/capture-presentation-fixture.ts <goalId>
 *
 * The only field with no captured source is the unsigned preview -- no trade has ever been
 * produced -- so it is constructed here from the real candidate and the real settlement
 * token, and labelled as such in the generated file.
 */
import { writeFileSync } from "node:fs";

import postgres from "postgres";

import { publicCandidate } from "@/lib/contracts";
import { PostgresGoalGuardRepository } from "@/lib/db/repository";
import { getMarketSeries } from "@/lib/market/service";

for (const file of [".env", ".env.local"]) {
  try { process.loadEnvFile(file); } catch { /* Not every environment ships this file. */ }
}

const DEFAULT_GOAL_ID = "248166b9-11e5-4f01-9688-b4ea4fce459f";
const OUTPUT = "src/lib/frontend/presentation/captured-run.ts";

const goalId = process.argv[2] ?? DEFAULT_GOAL_ID;
const repository = new PostgresGoalGuardRepository();

const ownerSessionHash = await repository.getGoalOwnerHash(goalId);
if (!ownerSessionHash) throw new Error(`Goal ${goalId} was not found.`);

const goal = await repository.getGoal(goalId, ownerSessionHash);
if (!goal) throw new Error(`Goal ${goalId} was not readable.`);
if (!goal.selectedCandidateId) throw new Error(`Goal ${goalId} has no selected candidate to present.`);
if (!goal.councilDecisionId) throw new Error(`Goal ${goalId} has no council decision to present.`);

const candidate = await repository.getCandidate(goal.selectedCandidateId, ownerSessionHash);
const decision = await repository.getDecision(goal.councilDecisionId, ownerSessionHash);
if (!candidate || !decision) throw new Error("The selected candidate or decision is missing.");

const series = await getMarketSeries(repository, 24);
const snapshot = series.at(-1) ?? null;
if (!snapshot) throw new Error("No market snapshot has been captured yet.");

// The goal-parse inference is not part of any entity the repository returns, but the composer
// surfaces its model and request ID, so it has to be captured too rather than typed by hand.
const sql = postgres(process.env.DATABASE_URL!, { ssl: "require", max: 1 });
const parseRow = (await sql`
  select id, model, request_id from gonka_inferences
  where goal_id = ${goalId} and purpose = 'goal_parse' and status = 'succeeded'
  order by created_at desc limit 1
`)[0];
await sql.end();
if (!parseRow) throw new Error(`Goal ${goalId} has no successful goal_parse inference.`);
const parseInference = { id: parseRow.id as string, model: parseRow.model as string, requestId: parseRow.request_id as string };

const summary = decision.reviews.map((review) => `${review.role}=${review.verdict}`).join(", ");
const literal = (value: unknown) => JSON.stringify(value, null, 2);

writeFileSync(OUTPUT, `// Generated by scripts/capture-presentation-fixture.ts -- do not edit by hand.
//
// A real completed run exported from the database (goal ${goalId}).
// Verdicts, models, Gonka request IDs, the candidate and the market snapshots are all
// exactly as they were recorded; nothing here is invented.
//
// Captured verdicts: ${summary}.
// The decision's own stored status is re-derived at read time by councilConsensus, so the
// current ruleset scores these real verdicts rather than replaying an outdated outcome.
import type { CouncilDecision, Goal, MarketSnapshot, ProtectionCandidate } from "@/lib/contracts";

export const capturedGoalId = ${literal(goalId)} as const;

export const capturedGoal: Goal = ${literal(goal)};

/** Internal shape: the presentation transport derives the public candidate from this. */
export const capturedCandidate: ProtectionCandidate = ${literal(candidate)};

export const capturedDecision: CouncilDecision = ${literal(decision)};

export const capturedSnapshot: MarketSnapshot = ${literal(snapshot)};

export const capturedSeries: MarketSnapshot[] = ${literal(series)};

/** The real goal-parse inference: the composer reports this model and request ID. */
export const capturedParseInference = ${literal(parseInference)} as const;
`);

console.log(`Wrote ${OUTPUT}`);
console.log(`  goal      ${goal.id} (${goal.goalType}, ${goal.protectedValueUsd} USD)`);
console.log(`  candidate ${candidate.id} strike ${candidate.strikeUsd} premium ${candidate.premiumUsd}`);
console.log(`  decision  ${decision.id} stored=${decision.status} (${summary})`);
console.log(`  market    ${series.length} snapshots, newest ${snapshot.capturedAt}`);
console.log(`  parse     ${parseInference.model} ${parseInference.requestId}`);
console.log(`  public candidate check: ${publicCandidate(candidate).id}`);

process.exit(0);
